### ISSUE TITLE
몇가지 궁굼한 점이 있습니다.

### ISSUE THREAD

**Issue by jongbok** [projectBS/S65#1]
여기에 남기는게 맞는지 모르겠지만, facebook에 남기는건 아닌것 같아 여기 남깁니다.

1. 코드에 완전항등식(===)을 사용하지 않으시던데 ES6에서는 완전항등식 구분이 없어진건가요?
2. 제가보기에는 constructor에 Object.defineProperties(...)으로 선언한 건 대부분 this.attr = 'val'; 형식으로 될거 같은데, 굳이 Object.defineProperties 로 선언한 이유가 있으신건가요?
3. Object.defineProperties() 는 ES5 API로 알고있는데, readonly를 구현할려면 get, set trap을 사용해야 하는건 아닌지요?(혹시나 ES5 에뮬레이터가 동작하지 않는지?)

추가로 이번주 스터디는 참석 할 수 없게 되었습니다.;;
좋은 강의 잘 듣고 있습니다. 감사합니다.

**Comment by hikaMaeng** [comment]
1
완전항등식은 방어적이라 좋은 선택입니다. ES6에서도 완전항등식의 구분이 있습니다. 단 타입이 동일한 인자임을 상식적인 범위 내에서  확신한다면 ==가 성능 상의 이득도 좀 있고 무엇보다 ===가 너무 긴 연산자라서 코드를 방해하는 경향이 있다보니 제가 잘 안쓰는 편이긴 하죠.
2
일단 열거불가나 읽기전용, 삭제불가 같은 속성은 그냥 this.attr = 3 으로는 만들 수 없습니다. 속성기술자를 사용하거나 defineProperty를 사용해야 하죠.
3
get, set trap은 무려 Proxy스펙입니다. readonly를 위해 프록시를 쓰는건 말이 안되죠 ^^;
오브젝트의 키를 인식하는 방법은 es5나 es6나 매일반입니다. 단지 es6에서는 심볼도 인식되는거라 큰 영향은 없습니다.

**Comment by jongbok** [comment]
혹시나 한 부분에 명퀘하게 답변 주셔서 감사합니다.
하지만, == 가 성능 상의 이득이 있다는 말에는 동의 하기 어렵습니다.
== 는 type이 틀릴경우 casting을 해야하기 때문에 type 검사비용은 동일하고, 오히려 casting비용이 들어갈 것 같습니다.
 
참고로  IE11,Chrome48에서 테스트시에 === 가 약간 좋은 성능이 나오는걸 확인 할 수 있었습니다.
https://jsperf.com/triple-equals-vs-twice-equals 
 
 
  
블로그서명박종복
자기소개를 입력하세요.  
-----Original Message-----
