### ISSUE TITLE
canvas 관련 코드리뷰 관련 질문입니다.

### ISSUE THREAD

**Issue by jongbok** [projectBS/S65#4]
1. readOnly 함수에서 for..in 구문에서 ES5라면 보통 prototype의 속성을 필터하기 위해서 if(target.hasOwnProperty(k)) 구문을 추가하는데 이런구문이 없는 이유가 있는건지요?

2. Display..dispatch 함수에서 for 구문안에서  listener를 호출하는데, 굳이 동기화 시킬필요가 없다면 dispatch함수가 빨리 응답하도록, setTimeout을 이용해서 비동기로 실행해 주는 것도 괜찮다고 생각하는데 어떻게 생각하시나요?

**Comment by hikaMaeng** [comment]
1. 내부에서만 사용될 목적이라 심층방어를 생략했습니다. 이 함수가 외부에 공개되어 사용되는 범용함수라면 보다 적극적으로 방어해야할테고 그럼 언급하신 내용이나 key를 따로 얻어서 루프도는 등의 처리를 추가해야할 것입니다.
2. 그것은 그것대로의 문제를 일으킵니다. 어떤 함수의 호출이 자동으로 비동기화 되는건 작성한 본인만 알 수 있지 외부에서는 알 수 없기 때문입니다. 오히려 외부에서 setTimeout(display.dispatch, 1000, 'loaded')  처럼 직접 컨트롤하게 하는게 나을 수도 있습니다. 선택의 문제죠. 실제 dispatch를 직접 호출하는 경우는 별로 없을 것입니다.
이미지태그의 경우 내부의 이미지가 로딩되면 호출하는 식이니까, 이미 비동기상태입니다.
https://github.com/projectBS/S65/blob/master/canvas/tags.js 의 Img구현체를 보시면 도움이 되실 듯합니다.
