### ISSUE TITLE
SVG pos 함수에 대한 아이디어 입니다.

### ISSUE THREAD

**Issue by jongbok** [projectBS/S65#5]
함수 인자로 {} 을 선호하지 않는다고 하셨지만;;
아래와 같이 하면 API를 사용하는 입장에서 코드량은 조금 늘지만 가독성이 더 높아 보입니다.

** Handler
SVGLine.prototype.pos = function(from, to) { return this.attr({ x1:from.x, y1:from.y, x2:to.x, y2:to.y }); };
SVGRect.prototype.bounds = function(v /*{x,y,width,height}*/) { return this.attr(v); };

** Client
line.pos(10, 10, 90, 60) -> line.pos({x:10, y:10}, {x:90, y:60})
rect.pos(110, 10, 80, 80) -> rect.bounds({x:110, y:10, width:80, height:80})

**Comment by overock** [comment]
그런 의미라면 코드상의 attr과 css가 충분히 역할을 하고 있다고 생각됩니다.
메소드명을 각자 따로 네이밍하는 건 고려해 보겠습니다.
